config/routes.rb
Rails.application.routes.draw do
  root 'mazes#index'

  resources :mazes do
    member do
      get :solve
    end
  end

end

app/models/maze.rb
class Array
  def longest_word
    group_by(&:size).max.last.first.size
  end
end

class Maze < ActiveRecord::Base
  belongs_to :input_type
  has_attached_file :maze_file

  validates_attachment_size :maze_file, :less_than => 1.megabytes
  validates_attachment :maze_file, content_type: { content_type: ["text/plain", "application/text"] }

  validates_presence_of :name
  validates_presence_of :maze
  validates_presence_of :start_x
  validates_presence_of :start_y
  validates_presence_of :stop_x
  validates_presence_of :stop_y
  validates_presence_of :wall
  validate :accept_one_char_for_wall
  validate :do_not_accept_asterisk
  validate :do_not_accept_asterisk_in_maze
  validate :start_stop_not_a_wall
  validate :start_stop_in_maze

  default_scope { order("created_at DESC") }


  def max_width
    self.maze.split("\r\n").longest_word
  end

  def max_height
    self.maze.split("\r\n").size
  end

  def accept_one_char_for_wall
    if self.wall.size > 1
      errors.add(:wall, "Must be one character")
    end
  end

  def do_not_accept_asterisk
    if self.wall == "*"
      errors.add(:wall, "Cannot be an asterisk")
    end
  end

  def do_not_accept_asterisk_in_maze
    if self.maze.include?("*")
      errors.add(:maze, "Cannot contain an asterisk")
    end
  end

  def start_stop_not_a_wall
    return true if self.maze.size == 0
    m = self.maze
    matrix = []
    m.split("\r\n").each do |line|
      matrix << line.split(//)
    end

    if matrix[self.start_y][self.start_x] == self.wall || matrix[self.stop_y][self.stop_x] == self.wall
      errors.add("Start or stop position is a wall", "")
    end
  end

  def start_stop_in_maze
    width = self.max_width
    height = self.max_height

    if !self.start_x.in?(0..width) || !self.stop_y.in?(0..height) || !self.stop_x.in?(0..width) || !self.stop_y.in?(0..height)
      errors.add("Start or stop position",  "is not in maze")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mazes_controller.rb
class MazesController < ApplicationController
  before_action :set_maze, only: [:show, :edit, :update, :destroy, :solve]
  def solve
    @matrix = BfsMaze.read_text(@maze.maze)
    @maze_solver = BfsMaze::BFSSolver.new(@matrix, @maze)
    @maze_solver.check_for_error
    @maze_solver.solve_maze
    @path = @maze_solver.path_array
rescue
    flash[:alert] = "Start or Goal cannot be a wall or outside maze!!!"
    redirect_to mazes_url
  end

  # GET /mazes
  # GET /mazes.json
  def index
    @mazes = Maze.all
  end

  # GET /mazes/1
  # GET /mazes/1.json
  def show
  end

  # GET /mazes/new
  def new
    @maze = Maze.new
  end

  # GET /mazes/1/edit
  def edit
  end

  # POST /mazes
  # POST /mazes.json
  def create
    if params[:maze][:maze_file].present?
      file = params[:maze][:maze_file]
      maze_hash = BfsMaze.parse_file(file.path)
      respond_to do |format|
        @maze = Maze.new(maze_hash)
        if @maze.save(maze_hash)
          format.html { redirect_to @maze, notice: 'Maze was successfully uploaded.' }
          format.json { render :show, status: :ok, location: @maze }
        else
          format.html { render :new }
          format.json { render json: @maze.errors, status: :unprocessable_entity }
        end
      end
    else
      @maze = Maze.new(maze_params)
      respond_to do |format|
        if @maze.save
          format.html { redirect_to @maze, notice: 'Maze was successfully created.' }
          format.json { render :show, status: :ok, location: @maze }
        else
          format.html { render :edit }
          format.json { render json: @maze.errors, status: :unprocessable_entity }
        end
      end
    end
  rescue EOFError
    flash[:alert] = "Error creating maze check your file input format!!!"
    redirect_to new_maze_url
  end

  # PATCH/PUT /mazes/1
  # PATCH/PUT /mazes/1.json
  def update
    if params[:maze][:maze_file].present?
      file = params[:maze][:maze_file]
      maze_hash = BfsMaze.parse_file(file.path)
      respond_to do |format|
        if @maze.update(maze_hash)
          format.html { redirect_to @maze, notice: 'Maze was successfully updated.' }
          format.json { render :show, status: :ok, location: @maze }
        else
          format.html { render :edit }
          format.json { render json: @maze.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        if @maze.update(maze_params)
          format.html { redirect_to @maze, notice: 'Maze was successfully updated.' }
          format.json { render :show, status: :ok, location: @maze }
        else
          format.html { render :edit }
          format.json { render json: @maze.errors, status: :unprocessable_entity }
        end
      end
    end
  rescue EOFError
    flash[:alert] = "Error creating maze check your file input format!!!"
    redirect_to new_maze_url
  end

  # DELETE /mazes/1
  # DELETE /mazes/1.json
  def destroy
    @maze.destroy
    respond_to do |format|
      format.html { redirect_to mazes_url, notice: 'Maze was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maze
      @maze = Maze.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maze_params
      params.require(:maze).permit(:name, :maze, :start_x, :start_y, :stop_x, :stop_y, :wall, :free_step, :maze_file)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mazes_helper.rb
module MazesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <%= render partial: 'shared/header' %>
    <%= render partial: 'shared/flash_messages' %>
      <div class="container">
        <%= yield %>
        <%= render partial: 'shared/footer' %>
      </div>
  </body>
</html>

app/views/mazes/_form.html.erb
<%= form_for(@maze, html: { multipart: true }) do |f| %>
    <div class="row">
      <div class="small-12 medium-4 large-4 columns">
        <h3>Upload a maze</h3>
        <%= f.label :maze_file %>
        <%= f.file_field :maze_file, required: true %>
      </div>
      <div class="small-12 medium-4 large-4 columns pull-4">
        <a href="#" data-reveal-id="mazeFormatModal" class="button tiny alert">Show maze format</a>
      </div>
    </div>
    <div class="row">
      <div class="small-12 medium-4 large-4 columns ">
        <div class="actions">
          <%= f.submit 'Upload', class: 'button tiny', maze: [] %>
        </div>
      </div>
    </div>
<% end %>

<%= form_for(@maze, html: { multipart: true }) do |f| %>
    <div class="row">
      <div class="small-12 columns">
        <% if @maze.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@maze.errors.count, "error") %> prohibited this maze from being saved:</h2>
              <ul>
                <% @maze.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
      </div>
    </div>
    <hr>
    <h3>Or create a maze</h3>
    <div class="row">
      <div class="small-12 medium-4 large-4 columns">
          <%= f.label :name %>
          <%= f.text_field :name %>
      </div>
      <div class="small-12 medium-4 large-4 columns">
        <%= f.label :start_x %>
        <%= f.number_field :start_x %>
      </div>
      <div class="small-12 medium-4 large-4 columns">
        <%= f.label :start_y %>
        <%= f.number_field :start_y %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 medium-4 large-4 columns">
        <%= f.label :wall %>
        <%= f.text_field :wall %>
      </div>
      <div class="small-12 medium-4 large-4 columns">
        <%= f.label :stop_x %>
        <%= f.number_field :stop_x %>
      </div>
      <div class="small-12 medium-4 large-4 columns">
        <%= f.label :stop_y %>
        <%= f.number_field :stop_y %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 medium-12 large-12 columns">
        <div class="field">
          <%= f.label :maze %>
          <%= f.text_area :maze, cols: 20, rows: 10 %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="small-12 medium-2 large-2 columns">
        <div class="actions">
          <%= f.submit action_name == 'new' || action_name == 'create' ? 'Create' : 'Update', class: 'button tiny' %>
        </div>
      </div>
    </div>

<% end %>
<!-- Reveal Modals begin -->
<div id="mazeFormatModal" class="reveal-modal" data-reveal aria-labelledby="mazeFormat" aria-hidden="true" role="dialog">
  <h2 id="mazeFormat">Maze format</h2>
  <p>Text format should be: </p>
  <p>
    <pre class="panel">
        Name of maze
        wall character
        start_x, start_y, stop_x, stop_y
        (0,0) (0,1) (0,2) (0,3) (0,4) ...
        (1,1) (1,2) (1,3) (1,4) (1,5) ...
        ....
    </pre>
    where (x,y) is the 'position' for each wall or free step of maze.
  </p>
  For example below is a maze called MyFirstMaze with walls represented with # character start at 1,1 stop(Goal) is at 4,8
  and after we have th maze representation
  <p>
      <pre class="panel">
          MyFirstMaze
          #
          1,1,4,8
          # ############
          # ############
          #  ###########
          ##  ##########
          ###  #########
          ##### ########
          ####  ########
          #### #########
          #### #########
          #### #########
      </pre>
  </p>
  <p>You can upload a maze file containing the above format or create a maze with the form provided</p>
  <h3>Maze example 2: Representing maze with binary values:</h3>
  <p>If 0 is wall you could have</p>
  <pre class="panel">
    MyIntMaze
    0
    0,0,5,5
    0111100000
    0001100011
    0111111111
    0011111111
    0000111111
    1100000001
    1100001001
    1111000011
  </pre>
  <p class="alert" style="color: red">MAze algorithm only cares for wall character. all other characters are treated as free steps</p>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>
<!-- Reveal Modals end -->

app/views/mazes/_maze.html.erb
<div class="row">
  <div class="small-12 columns">
        <ul class="pricing-table">
          <li class="title"><%= link_to maze.name, maze_path(maze) %></li>
            <li class="price">
              <canvas id="mazeCanvas-<%= maze.id %>" width="640" height="450" style="border:1px solid #000000;">
                No canvas supported
                  <%= maze.maze %>
              </canvas>
            </li>
          <li class="description">Start: <%= maze.start_x %>, <%= maze.start_y %></li>
          <li class="description">Stop: <%= maze.stop_x %>, <%= maze.stop_y %></li>
          <li class="bullet-item">Wall: <%= maze.wall %></li>
          <li class="cta-button">
            <%= link_to_unless_current 'Show', maze %>
            <%= link_to_unless_current 'Edit', edit_maze_path(maze) %>
            <%= link_to 'Destroy', maze, method: :delete, data: { confirm: 'Are you sure?' } %>
          </li>
          <li class="cta-button">
            <%= link_to 'Solve', solve_maze_path(maze), class: 'button tiny' %>
          </li>
        </ul>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        // fill
        var c = document.getElementById("mazeCanvas-<%= maze.id %>");
        var ctx = c.getContext("2d");

        var s_start_x = "<%= maze.start_x %>";
        var s_start_y = "<%= maze.start_y %>";
        var g_stop_x = "<%= maze.stop_x %>";
        var g_stop_y = "<%= maze.stop_y %>";

        var maze_width = "<%= maze.max_width %>";
        var maze_height = "<%= maze.max_height %>";
        var canvas_width = c.width;
        var canvas_height = c.height;
        var room_w = 12;
        var room_h = 12;

        // make canvas width and height dynamic
        c.width = maze_width * room_w;
        c.height=maze_height * room_h;

        // fill maze background with a light grey color
        ctx.fillStyle = "#eee";
        ctx.fillRect(0,0,maze_width*room_w,maze_height*room_h);
        ctx.fillStyle = "#000";

        ctx.fillStyle = "#000";
        var start_x = 0;
        var start_y = 0;

        <% matrix = BfsMaze.read_text(maze.maze) %>

        <% matrix.each_index do |row| %>
            <% matrix[row].each do |col| %>
                <% if col == maze.wall %>
                    // draw wall
                    ctx.fillRect(start_x, start_y, room_w, room_h);
                <% end %>
                start_x += room_w;
            <% end %>
            start_x = 0;
            start_y += room_h;
        <% end %>

        // fill start with blue color
        ctx.fillStyle = "#0000ff";
        ctx.fillRect(s_start_x*room_w, s_start_y*room_h, room_w, room_h);

        // fill goal with red color
        ctx.fillStyle = "#ff0000";
        ctx.fillRect(g_stop_x * room_w, g_stop_y * room_h, room_w, room_h);

        // draw text S, G
        ctx.fillStyle = "#000000";
        ctx.font = "12px Georgia";
        ctx.fillText('S', s_start_x * room_w + 4, s_start_y * room_h + 10 );
        ctx.fillText('G', g_stop_x*room_w + 4 , g_stop_y * room_h + 10);
    });
</script>

app/views/mazes/edit.html.erb
<div class="row">
  <div class="row">
    <div class="small-12 columns">
      <h1>Edit Maze</h1>
    </div>
  </div>
  <div class="small-12 columns">
    <%= link_to 'Back', mazes_path %>
    <%= render 'form' %>
  </div>
</div>

app/views/mazes/index.html.erb
<h3>Listing Mazes</h3>

<%= render @mazes %>

app/views/mazes/new.html.erb
<h1>New Maze</h1>

<%= render 'form' %>

<%= link_to 'Back', mazes_path %>

app/views/mazes/show.html.erb
<%= render @maze %>

app/views/mazes/solve.html.erb
<div class="row">
  <div class="small-12 columns">
    <div class="maze-original">
      <div class="maze">
        <h3>Maze to solve:</h3>
            <canvas id="mazeToSolveCanvas">
                <pre>
                    <% @matrix[@maze.start_y][@maze.start_x] = 'S' %>
                  <% @matrix[@maze.stop_y][@maze.stop_x] = 'G' %>
                  <% @matrix.each_index do |index| %>
                        <%= @matrix[index].join %>
                    <% end %>
                  <% @matrix[@maze.start_y][@maze.start_x] = '-' %>
                  <% @matrix[@maze.stop_y][@maze.stop_x] = '-' %>
                </pre>
            </canvas>
      </div>
    </div>
  </div>
  <hr>
  <div class="small-12 columns">
    <div class="solvedMaze">
      <div class="maze">
        <% if @maze_solver.status.found %>
            <div class="maze">
              <h3>
                Solved maze
              </h3>
              <canvas id="solvedMazeCanvas" width="640" height="450" style="border:1px solid #000000;">
                No canvas supported
              </canvas>
              <h3>Path from S to G: (x,y) </h3>
                <pre>
                <% @path.each do |p| %>
                  <%= p %>
                <% end %>
                </pre>
        <% else %>
            <h3>Maze could not be solved</h3>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% if @maze_solver.status.found %>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function(){
            // fill
            var c = document.getElementById("solvedMazeCanvas");
            var ctx = c.getContext("2d");

            var s_start_x = "<%= @maze.start_x %>";
            var s_start_y = "<%= @maze.start_y %>";
            var g_stop_x = "<%= @maze.stop_x %>";
            var g_stop_y = "<%= @maze.stop_y %>";


            var maze_width = "<%= @maze.max_width %>";
            var maze_height = "<%= @maze.max_height %>";
            var canvas_width = c.width;
            var canvas_height = c.height;
            var room_w = 25;
            var room_h = 25;

            // make canvas width and height dynamic
            c.width = maze_width * room_w;
            c.height=maze_height * room_h;

            // fill maze background with a light grey color
            ctx.fillStyle = "#eee";
            ctx.fillRect(0,0,maze_width*room_w,maze_height*room_h);
            ctx.fillStyle = "#000";

            ctx.fillStyle = "#000";
            var start_x = 0;
            var start_y = 0;
            <% @matrix.each_index do |row| %>
            <% @matrix[row].each do |col| %>
            <% if col == @maze.wall %>
            // draw wall
            ctx.fillRect(start_x, start_y, room_w, room_h);
            <% end %>
            start_x += room_w;
            <% end %>
            start_x = 0;
            start_y += room_h;
            <% end %>

            // print path with green color
            ctx.fillStyle = "#00ff00";
            <% @maze_solver.yield_path do |x, y| %>
            start_x = <%= x %>;
            start_y = '<%= y %>';
            ctx.fillRect(start_x*room_w, start_y*room_h, room_w, room_h);
            <% end %>

            // fill start with blue color
            ctx.fillStyle = "#0000ff";
            ctx.fillRect(s_start_x*room_w, s_start_y*room_h, room_w, room_h);

            // fill goal with red color
            ctx.fillStyle = "#ff0000";
            ctx.fillRect(g_stop_x * room_w, g_stop_y * room_h, room_w, room_h);

            // draw S, G
            ctx.fillStyle = "#000000";
            ctx.font = "15px Georgia";
            ctx.fillText('S', s_start_x * room_w + 8, s_start_y * room_h + 19 );
            ctx.fillText('G', g_stop_x*room_w + 8, g_stop_y * room_h + 19);
        });
    </script>
<% end %>

<
<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        // fill
        var c = document.getElementById("mazeToSolveCanvas");
        var ctx = c.getContext("2d");

        var s_start_x = "<%= @maze.start_x %>";
        var s_start_y = "<%= @maze.start_y %>";
        var g_stop_x = "<%= @maze.stop_x %>";
        var g_stop_y = "<%= @maze.stop_y %>";

        var maze_width = "<%= @maze.max_width %>";
        var maze_height = "<%= @maze.max_height %>";
        var canvas_width = c.width;
        var canvas_height = c.height;
        var room_w = 12;
        var room_h = 12;

        // make canvas width and height dynamic
        c.width = maze_width * room_w;
        c.height=maze_height * room_h;

        // fill maze background with a light grey color
        ctx.fillStyle = "#eee";
        ctx.fillRect(0,0,maze_width*room_w,maze_height*room_h);
        ctx.fillStyle = "#000";

        ctx.fillStyle = "#000";
        var start_x = 0;
        var start_y = 0;

        <% matrix = BfsMaze.read_text(@maze.maze) %>

        <% matrix.each_index do |row| %>
            <% matrix[row].each do |col| %>
                <% if col == @maze.wall %>
                    // draw wall
                    ctx.fillRect(start_x, start_y, room_w, room_h);
                <% end %>
                start_x += room_w;
                <% end %>
            start_x = 0;
            start_y += room_h;
        <% end %>

        // fill start with blue color
        ctx.fillStyle = "#0000ff";
        ctx.fillRect(s_start_x*room_w, s_start_y*room_h, room_w, room_h);

        // fill goal with red color
        ctx.fillStyle = "#ff0000";
        ctx.fillRect(g_stop_x * room_w, g_stop_y * room_h, room_w, room_h);

        // draw text S, G
        ctx.fillStyle = "#000000";
        ctx.font = "12px Georgia";
        ctx.fillText('S', s_start_x * room_w + 4, s_start_y * room_h + 10 );
        ctx.fillText('G', g_stop_x*room_w + 4 , g_stop_y * room_h + 10);
    });
</script>

app/views/shared/_flash_messages.html.erb
<div class="flass_message">
  <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
          <div data-alert class="alert-box <%= name %>">
            <%= msg %>
            <button href="#" class="close">&times;</button>
          </div>
      <% end %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="panel">
    <div class="row">
      <div class="small-12 columns">
      </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Maze solve', root_path %></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class=""><%= link_to 'New maze', new_maze_path %></li>
      <li class=""><%= link_to 'Mazes', mazes_path %></li>
    </ul>
  </section>
</nav>